config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: "pages#index"
  resources :blogs, only: [:index, :show, :create, :new, :edit, :update, :destroy]
  resources :contacts, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, uniqueness: true, presence: true
    # validates :image, presence: true
    validates :post, presence: true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      validate: true
  attribute :email,     validate: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   validate: true, length: { minimum: 12 }
  attribute :nickname,  captcha: true # For Bots

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact via site",
      :to => "Rztprog@outlook.fr",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :set_blog, only: [:show, :edit, :update]

    def index
        @blogs = Blog.all
        # faire un triage par plus récent
    end

    def show
    end

    def new
        @blog = Blog.new
        # authorize @list
    end

    def create
        @blog = Blog.new(blog_params)
        # @list.user = current_user
        # authorize @list

        if @blog.save
            redirect_to blogs_path
        else
            render :new
        end
    end

    def update
        @blog.update(blog_params)
        redirect_to blog_path(@blog)
    end

    private

    def set_blog
        @blog = Blog.find(params[:id])
    end

    def blog_params
        params.require(:blog).permit(:title, :post, :image)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  add_flash_types :info, :error, :warning

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Message sent!'
    else
      flash.now[:error] = 'Could not send message !'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def index
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/edit.html.erb
<div class="container">
  <h1>Edit article</h1>

  <div class="blog-buttons-container blog-buttons-container-form">
    <div class="blog-button">
      <%= link_to blogs_path do %>
        <i class="fa-solid fa-angles-left"></i> Back
      <% end %>
    </div>
  </div>

  <%= simple_form_for(@blog) do |f| %>
    <%= f.input :title, label: "Article title", placeholder: "Ex: A new feature in Rails" %>
    <br>
    <%= f.input :image, as: :file, class: "imageButton", label: "Article image" %>
    <br>
    <%= f.input :post, as: :text, label: "Article content", placeholder: "Ex: Describe this new feature" %>
    <br>
    <%= f.button :submit, "Edit", class: "createButton" %>
  <% end %>

</div>

app/views/blogs/index.html.erb
<div class="container">
  <!-- <h1>Blogs index</h1> -->
  <div class="blogs-nav">
    <form class="search-blogs-form">
      <input class="" type="search" placeholder="Search..." aria-label="Search" name="search" value="<%= params[:search] if params[:search] %>">
      <button class="search-blogs-button" type="submit">
        <i class="fa-solid fa-magnifying-glass"></i>
      </button>
    </form>
    <div class="blog-button">
      <%= link_to new_blog_path do %>
        <i class="fa-solid fa-plus"></i>
        <span>ADD</span>
      <% end %>
    </div>
  </div>
  <div class="blogs-grid-index">
    <% @blogs.each do |blog| %>
      <div class="blog-card-container">
        <%= link_to edit_blog_path(blog), class: "edit-blog" do %>
          <i class="fa-regular fa-pen-to-square"></i>
        <% end %>
        <%= link_to blog_path(blog) do %>
          <div class="blogs-card-border">
            <div class="blogs-card">
              <p><%= blog.title %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="container">
  <h1>New article</h1>
  <div class="blog-buttons-container blog-buttons-container-form">
    <div class="blog-button">
      <%= link_to blogs_path do %>
        <i class="fa-solid fa-angles-left"></i> Back
      <% end %>
    </div>
  </div>
  <%= simple_form_for(@blog) do |f| %>
    <%= f.input :title, label: "Article title", placeholder: "Ex: A new feature in Rails" %>
    <br>
    <%= f.input :image, as: :file, class: "imageButton", label: "Article image" %>
    <br>
    <%= f.input :post, as: :text, label: "Article content", placeholder: "Ex: Describe this new feature" %>
    <br>
    <%= f.button :submit, "Create", class: "createButton" %>
  <% end %>
</div>

app/views/blogs/show.html.erb
<div class="container">
  <div class="blog-buttons-container">
    <div class="blog-button">
      <%= link_to blogs_path do %>
        <i class="fa-solid fa-angles-left"></i> Back
      <% end %>
    </div>
    <div class="blog-button">
      <%= link_to edit_blog_path(@blog) do %>
        <i class="fa-regular fa-pen-to-square"></i> Edit
      <% end %>
    </div>
  </div>
  <section class="blog-header">
      <p><%= @blog.title %></p>
  </section>
  <div class="credit">
    <p>By USER posted <%= @blog.created_at %></p>
  </div>
  <article class="blog-post">
    <%= @blog.post %>
  </article>
</div>

app/views/contacts/create.html.erb
<div class="container">
  <h1>Contact Form</h1>

  <h3>Thank you for your message!</h3>
</div>

app/views/contacts/new.html.erb
<div class="contact-container">
  <h1>Contact me on</h1>

  <ul class="social-list">
    <li class="social-contact"><a class="social-contact-link" href="https://twitter.com/rztprog"><i class="fab fa-twitter"></i></a></li>
    <li class="social-contact"><a class="social-contact-link" href="https://github.com/rztprog"><i class="fab fa-github"></i></a></li>
    <li class="social-contact"><a class="social-contact-link" href="mailto:rztprog@outlook.fr"><i class='fas fa-envelope'></i></a></li>
  </ul>

  <h2 class="social-h2">OR</h2>

  <% flash.each do |key, message| %>
    <p class="alert-contact alert-<%= key %>"><%= message %></p>
  <% end %>

  <%= form_for @contact do |f| %>
    <ul class="contact-form-list">
      <li class="input-wrapper">
        <!-- <%= f.label :name %> -->
        <%= f.text_field  :name, required: true, class: "contact-form-field", 
                          placeholder: "Name" %>      
      </li>

      <li class="input-wrapper">
      <!-- <%= f.label :email %> -->
      <%= f.text_field :email, required: true, class: "contact-form-field",  
                        placeholder: "Email"%>
      </li>

      <li class="input-wrapper-textarea">
      <!-- <%= f.label :message %> -->
      <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-field", 
                      placeholder: "Message"%>
      </li>

      <!-- Anti B0ts -->
      <div class= "b0t-display">
        <%= f.label :nickname %>
        <%= f.text_field :nickname, :hint => 'An71B07' %>
      </div>

      <%= f.submit 'Send', class: 'send-button' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%#= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body class="body">
    <%= render "shared/navbar" %>
    <%= yield %>
    <% flash.each do |key, message| %>
      <p class="alert alert-<%= key %>"><%= message %></p>
    <% end %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
  <p>Root</p>
  <i class="fa-regular fa-pen-to-square"></i>
  <%= icon('fa-brands', 'font-awesome')%>
  <%= icon('fa-solid', 'user-secret')%>
  <%= icon('fa-regular', 'bell')%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <ul class="navbar-list">
    <li><%= link_to "ROOT", root_path %></li>
    <li><%= link_to "WORK", root_path %></li>
    <li><%= link_to "BLOG", blogs_path, class: "#{'current-list' if controller_name == 'blogs'}" %></li>
    <li><%= link_to "CONTACT", new_contact_path, class: "#{'current-list' if controller_name == 'contacts'}" %></li>
  </ul>
  <div class="redline"></div>
</nav>